- project:
    templates:
      - publish-to-pypi
    check:
        jobs:
          - openstack-tox-py38
          - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
